version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - "db:mysql"
    container_name: christmas_gift_backend
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    container_name: christmas_db
    environment:
      MYSQL_ROOT_PASSWORD: "waernpeder"
      MYSQL_DATABASE: "test"
      
    
