version: '2'
services:
  web:
    #mem_limit: 200m
    build: .
    ports:  
      - "80:8080"
    links:
      - "db:mysql"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    # mem_limit: 50m
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "waernpeder"
      MYSQL_DATABASE: "test"
      
    
