version: '2'
services:
  backend:
    #mem_limit: 200m
    container_name: xmas_java_backend
    build: .
    ports:  
      - "80:8080"
      - "5005:5005"
    links:  
      - "db:mysql"
      - "mail_backend:mailserver"
    depends_on:
      - db
  db:
    image: mysql:5.7  
    # mem_limit: 50m
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "waernpeder"
      MYSQL_DATABASE: "test"
  mail_backend:
    container_name: xmas_mail_backend
    build: ../mail/
    ports: 
      - "5000:5000"
    
